# Generated by Django 2.2.7 on 2019-12-01 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_shop_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinates',
            old_name='lon',
            new_name='lng',
        ),
    ]
